name: name: Import labels
on:
    push:
        paths:
            - docs/labels.json

jobs:
    labels:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: checkout source files
              uses: actions/checkout@v2

            - name: use node.js v${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with: node-version ${{ matrix.node-version }}

            - name: install dependencies
              run: npm ci

            - name: import labels
              if: github.ref == 'refs/heads/master'
              run: |
                  npx ghlbl -o yapyeeqiang -r issues-label -t ${{ secrets.GITHUB_TOKEN }} -d
                  npx ghlbl -o yapyeeqiang -r issues-label -t ${{ secrets.GITHUB_TOKEN }} -i docs/labels.json
