name: Import labels
on:
    push:
        branches: [master]

jobs:
    labels:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout source files
              uses: actions/checkout@v2

            - name: Use node.js v${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Install github-label-template
              run: npm install github-label-template

            - name: Remove existing labels
              run:
                  npx ghlbl -o ${{ github.repository_owner }} -r ${{
                  github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
                  -d

            # - name: Import labels from docs/labels.json
            #   run:
            #       npx ghlbl -o ${{ github.repository_owner }} -r ${{
            #       github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
            #       -i docs/labels.json
