name: GitHub Issue Labels Template

on:
    push:
        branches: [master]

jobs:
    labels:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source files
            - uses: actions/checkout@v2

            - name: setup node
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependency
              run: npm install github-label-template
              shell: bash

            - name: Delete existing labels
              run:
                  npx ghlbl -o ${{ github.repository_owner }} -r ${{
                  github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
                  -d
              shell: bash

            - name: Import labels from json file
              run:
                  npx ghlbl -o ${{ github.repository_owner }} -r ${{
                  github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}
                  -i docs/labels.json
              shell: bash
